### ISSUE TITLE
Add OS Path for example: /dev/sda

### ISSUE THREAD

**Issue by ghost** [omame/megaclisas-status#6]
Hi,
There is a guy called Vincent S. Cojot who modified the script to include the OS Path in the output table.
This feature was invaluable to me and I want to be upstream so that people can have it right away.
You can find the modified script here:
https://github.com/lordadamson/megaclisas-status

**Comment by omame** [comment]
Unfortunately my circumstances have changed and I don't have an environment to work on megaclisas-status anymore.
If you send can a pull request with some proven tests attached I'll make sure to promptly merge it in.
